### ISSUE TITLE
check-cloudwatch-metric.rb always fails with undefined method `empty?'

### ISSUE THREAD

**Issue by elwarren** [sensu-plugins/sensu-plugins-aws#105]
While attempting to use sensu plugin check-cloudwatch-metric.rb it always fails with the following error:

```
Check failed to run: undefined method `empty?' for 10:Fixnum, ["/Users/wlindsey/work/sensu/sensu-plugins-aws.github/lib/sensu-plugins-aws/cloudwatch-common.rb:13:in `resp_has_no_data'", "/Users/wlindsey/work/sensu/sensu-plugins-aws.github/lib/sensu-plugins-aws/cloudwatch-common.rb:45:in `check'", "/Users/wlindsey/work/sensu/sensu-plugins-aws.github/bin/check-cloudwatch-metric.rb:115:in `run'", "/Users/wlindsey/.rvm/gems/ruby-2.0.0-p643/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in `block in <class:CLI>'"]
```

Seems the you cannot ask a length method if it is empty?

Attaching pull request.

**Comment by sstarcher** [comment]
#106 closes
