### ISSUE TITLE
uninitialized constant CheckRDSEvents::Common (NameError)

### ISSUE THREAD

**Issue by obazoud** [sensu-plugins/sensu-plugins-aws#129]
I try to use new RDS check: check-rds-pending.rb but I experienced some issues:

```
# /opt/sensu/embedded/bin/check-rds-pending.rb
Sensu::Plugin::CLI: ["Not implemented! You should override Sensu::Plugin::CLI#run."]
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-aws-3.1.0/bin/check-rds-pending.rb:37:in `<class:CheckRDSEvents>': uninitialized constant CheckRDSEvents::Common (NameError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-aws-3.1.0/bin/check-rds-pending.rb:36:in `<top (required)>'
	from /opt/sensu/embedded/bin/check-rds-pending.rb:22:in `load'
	from /opt/sensu/embedded/bin/check-rds-pending.rb:22:in `<main>'
```

```
/opt/sensu/embedded/bin/check-rds-pending.rb -r eu-west-1
Invalid check argument(s): invalid option: -r, ["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:13:in `initialize'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `new'", "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:55:in `block in <class:CLI>'"]
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-aws-3.1.0/bin/check-rds-pending.rb:37:in `<class:CheckRDSEvents>': uninitialized constant CheckRDSEvents::Common (NameError)
	from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugins-aws-3.1.0/bin/check-rds-pending.rb:36:in `<top (required)>'
	from /opt/sensu/embedded/bin/check-rds-pending.rb:22:in `load'
	from /opt/sensu/embedded/bin/check-rds-pending.rb:22:in `<main>'
```

sensu: 0.23.2-2 amd64
sensu-plugins-aws: 3.1.0

 Any idea ?

**Comment by obazoud** [comment]
Close #130
