### ISSUE TITLE
handler-ec2_node.rb sdk conflict

### ISSUE THREAD

**Issue by runningman84** [sensu-plugins/sensu-plugins-aws#134]
is this a known problem?
```
{"timestamp":"2016-07-01T07:17:13.378147+0000","level":"info","message":"handler output","handler":{"type":"pipe","filters":["keepalives","ec2"],"severities":["warning","critical"],"command":"handler-ec2_node.rb","timeout":300,"name":"ec2_node"},"output":["/opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate sensu-plugins-aws-3.1.0, because aws-sdk-2.3.19 conflicts with aws-sdk (= 2.2.28) (Gem::ConflictError)\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:200:in `rescue in try_activate'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:193:in `try_activate'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'\n\tfrom /opt/sensu/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'\n\tfrom /opt/sensu/embedded/bin/handler-ec2_node-custom.rb:144:in `<main>'\nonly handling every 60 occurrences: server1-ubuntu-1404/keepalive\n"]}
```

**Comment by eheydrick** [comment]
Hi @runningman84, that shouldn't be happening. Can you paste the output of `/opt/sensu/embedded/bin/gem list aws`. Sounds like you have a newer aws-sdk installed than what the plugin expects.

**Comment by runningman84** [comment]
sure:
```
/opt/sensu/embedded/bin/gem list aws

*** LOCAL GEMS ***

aws-sdk (2.3.19, 2.2.28)
aws-sdk-core (2.3.19, 2.2.28)
aws-sdk-resources (2.3.19, 2.2.28)
aws-sdk-v1 (1.66.0)
fog-aws (0.9.4)
right_aws (3.1.0)
sensu-plugins-aws (3.1.0)
```
This is a fresh install using this cookbook:
https://github.com/runningman84/chef-monitor

**Comment by runningman84** [comment]
Maybe the aws cookbook requires a newer version?

**Comment by sstarcher** [comment]
@runningman84 do you know where ```aws-sdk 2.2.28``` is coming from?

**Comment by sstarcher** [comment]
So it looks like aws-sdk 2.2.8 is coming from sensu-aws 3.1.

The un-released master branch has been updated to require ~> 2.3 instead of a hard dependency on 2.2.8.  After master is released your issue should go away.

**Comment by eheydrick** [comment]
[3.2.0](https://github.com/sensu-plugins/sensu-plugins-aws/releases/tag/3.2.0) has the relaxed pin on `aws-sdk`.
