### ISSUE TITLE
Deprecation Warnings?

### ISSUE THREAD

**Issue by ninjada** [sensu-plugins/sensu-plugins-aws#149]
Just testing these plugins and getting some deprecations warnings which is messing up the alerts in sensu:

eg

```
/opt/sensu/embedded/bin/ruby ./check-elb-health.rb -a <accessid> -k <accesskey> -r ap-southeast-2 -n sensu-ELB -v

Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/right_http_connection-1.5.0/lib/base/net_fix.rb:51:in `rbuf_fill': Object#timeout is deprecated, use Timeout.timeout instead.
/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/right_http_connection-1.5.0/lib/base/net_fix.rb:51:in `rbuf_fill': Object#timeout is deprecated, use Timeout.timeout instead.
```
/opt/sensu/embedded/bin/ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

**Comment by majormoses** [comment]
@ninjada I see the warning deprecation but it does not break for me, what version of the gem are you using?
```$ ./bin/check-elb-health.rb -r us-west-2 -n dev-pub-elb-sensu -v
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
ELBHealth OK: All instances on ELB us-west-2::dev-pub-elb-sensu healthy!
```

We can either look at solving this by using aws sdk and not using `right_aws` which uses `right_http_connection` or fix the upstream issue where there is an issue filed (https://github.com/rightscale/right_http_connection/issues/31) for the deprecation warnings.

**Comment by majormoses** [comment]
Given the lack of active development (last commit was Aug 19, 2014 with outstanding prs to fix this) on `right_http_connection` I would say we should re-write with `aws-sdk`
