### ISSUE TITLE
handler-ec2_node - No Authorization Error

### ISSUE THREAD

**Issue by ninjada** [sensu-plugins/sensu-plugins-aws#150]
Hello, attempting to get the handler-ec2_node plugin working to remove aws clients that are terminated or stopped.

have the following configuration

```
cat /etc/sensu/conf.d/ec2_node.json
{
  "filters": {
     "ghost_nodes": {
       "attributes": {
         "check": {
           "name": "keepalive",
           "status": 2
         },
         "occurences": "eval: value =2"
       }
     }
   },
  "handlers": {
    "ec2_node": {
       "type": "pipe",
       "command": "/etc/sensu/plugins/handler-ec2_node.rb",
       "severities": ["ok", "unknown", "warning", "critical"], # Note: unless i added 'ok' and 'unknown' i saw errors.
       "filter": "ghost_nodes"
    }
  }
}

cat /etc/sensu/conf.d/ec2_states.json 
{
  "ec2_node": {
    "ec2_states": [
      "terminated",
      "stopping",
      "shutting-down",
      "stopped"
    ]
   }
}
```

I have a sensu-client connected, with it's ec2 instance id as the client name. I power it off and wait for the keepalive warning, but only see the following error in the sensu logs:

```
{
  "timestamp": "2016-08-24T00:24:51.449000+0000",
  "level": "info",
  "message": "handler output",
  "handler": {
    "type": "pipe",
    "command": "/etc/sensu/plugins/handler-ec2_node.rb",
    "severities": [
      "ok",
      "unknown",
      "warning",
      "critical"
    ],
    "filter": "ghost_nodes",
    "name": "ec2_node"
  },
  "output": [
    "/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call': You are not authorized to perform this operation. (Aws::EC2::Errors::UnauthorizedOperation)\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/plugins/response_target.rb:21:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/request.rb:70:in `send_request'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.5.5/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'\n\tfrom /etc/sensu/plugins/handler-ec2_node.rb:191:in `ec2_node_should_be_deleted?'\n\tfrom /etc/sensu/plugins/handler-ec2_node.rb:164:in `handle'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.3.0/lib/sensu-handler.rb:57:in `block in <class:Handler>'\n"
  ]
}
```

As per the plugin info I've tried creating a file at /etc/sensu/conf.d/aws.json with details of an IAM user with full admin access profile:

```
{
  "aws": {
    "access_key": "mykey",
    "secret_key": "mykey",
    "region": "ap-southeast-2"
   }
}
```

Have also used the 'aws configure' option to set the credentials as well as creating  /etc/profile.d/aws-key.sh with my key values as exports. Still get the auth error above.

What am I doing wrong?

**Comment by obazoud** [comment]
Which version of sensu-plugins-aws do you use ?
Do you allow "ec2:DescribeInstances" in IAM ?

**Comment by sstarcher** [comment]
@ninjada That issue is coming from AWS.  Verify that your keys have the correct permissions.

**Comment by ninjada** [comment]
sensu-plugins-aws was latest from this repo, so handler-ec2_node.rb was current 3month old one.

IAM user had full admin permissions eg.

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "*",
      "Resource": "*"
    }
  ]
}
```

This only worked if i deployed my sensu master with an IAM role baked in....

**Comment by runningman84** [comment]
using an IAM profile is best practice anyway...

**Comment by majormoses** [comment]
@ninjada are you still seeing this? If so could you try using a check that for sure works? This will allow us to verify environment issue vs an issue in the code

**Comment by majormoses** [comment]
closing due to inactivity
