### ISSUE TITLE
handler-ec2_node - missing credentials

### ISSUE THREAD

**Issue by olivierpilotte** [sensu-plugins/sensu-plugins-aws#168]
In the handler documentation:

`
{
  "aws": {
    "access_key": "adsafdafda",
    "secret_key": "qwuieohajladsafhj23nm",
    "region": "us-east-1c"
  }
}
`

Does not seem to work. I tried many different ways to try to make this work, with no luck.
I'm not a Ruby programmer either, so I'm a bit confused about how these credentials are passed to the AWS client.

**Comment by runningman84** [comment]
duplicate of https://github.com/sensu-plugins/sensu-plugins-aws/issues/150

**Comment by olivierpilotte** [comment]
Actually, it's not really a duplicate. I'm trying to follow the documentation and it doesn't work. It's not an Unauthorized issue, it's a Missing credentials issue.

**Comment by Maraumax** [comment]
I have same problem: configuration is set in /opt/sensu/conf.d/aws.json with same content than @olivierpilotte but i have this error:
```
["/opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/request_signer.rb:100:in `require_credentials': unable to sign request without credentials set (Aws::Errors::MissingCredentialsError)\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/request_signer.rb:90:in `sign_authenticated_requests'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/request_signer.rb:83:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/retry_errors.rb:87:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/query/handler.rb:27:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/seahorse/client/plugins/endpoint.rb:41:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/seahorse/client/plugins/response_target.rb:21:in `call'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/seahorse/client/request.rb:70:in `send_request'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.6.19/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'\n\tfrom /etc/sensu/handlers/ec2_node.rb:191:in `ec2_node_should_be_deleted?'\n\tfrom /etc/sensu/handlers/ec2_node.rb:164:in `handle'\n\tfrom /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-plugin-1.4.2/lib/sensu-handler.rb:81:in `block in <class:Handler>
```
maybe sensu update?

**Comment by majormoses** [comment]
@olivierpilotte @Maraumax  you really should rely on IAM (for everything but local development) and ENV variables (for local development).

I agree this is not the same issue referenced above and I am inclined to update our documentation remove this method as it's apparently broken and a less preferable solution imho. Currently this plugin suffers from many authentication issues and we need to eventually get around to doing this for all checks and handlers (I have implemented it for a few but have limited bandwidth and would welcome a contribution on this): https://github.com/sensu-plugins/sensu-plugins-aws/issues/2#issuecomment-112544621
