### ISSUE TITLE
check-cloudwatch-metric.rb doesn't accept absence of dimentions

### ISSUE THREAD

**Issue by ay-b** [sensu-plugins/sensu-plugins-aws#229]
`check-cloudwatch-metric.rb -r us-east-1 --namespace AWS/RDS -m DatabaseConnections -p 60 -w 5 -c 2` resulting a message:
>Check failed to run: expected params[:dimensions] to be an Array, got value “” (class: String) instead., [“/Users/suncheez/.rvm/gems/ruby-2.4.0/gems/aws-sdk-core-2.10.21/lib/aws-sdk-core/param_validator.rb:28:in `validate!‘”

But Json is ok about absence of dimensions (this is an aggregated metric for all RDS instances):
```
        {
            "Namespace": "AWS/RDS", 
            "Dimensions": [], 
            "MetricName": "DatabaseConnections"
        },
```

**Comment by majormoses** [comment]
This issue is that we are assuming that there always is a '=' to split on here: https://github.com/sensu-plugins/sensu-plugins-aws/blob/7.0.0/bin/check-cloudwatch-metric.rb#L108

**Comment by majormoses** [comment]
I thought initially understood the bug but this is kinda odd:
```
$ bundle exec ./bin/check-cloudwatch-metric.rb -r us-east-1 --namespace AWS/RDS -m DatabaseConnections -p 60 -w 5 -c 2
Check failed to run: expected params[:dimensions] to be an Array, got value "" (class: String) instead., ["/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/param_validator.rb:28:in `validate!'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/param_validator.rb:13:in `validate!'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/plugins/response_target.rb:21:in `call'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/request.rb:70:in `send_request'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/aws-sdk-core-2.10.22/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'", "/home/babrams/projects/personal/sensu/sensu-plugins-aws/lib/sensu-plugins-aws/cloudwatch-common.rb:87:in `check'", "./bin/check-cloudwatch-metric.rb:121:in `run'", "/home/babrams/.rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sensu-plugin-2.1.0/lib/sensu-plugin/cli.rb:58:in `block in <class:CLI>'"]
```
vs
```
$ bundle exec ./bin/check-cloudwatch-metric.rb -r us-east-1 --namespace AWS/RDS -m DatabaseConnections -d '' -p 60 -w 5 -c 2
CloudWatchMetricCheck UNKNOWN: AWS/RDS-DatabaseConnections() could not be retrieved
```
Considering that the default is also an empty string this: https://github.com/sensu-plugins/sensu-plugins-aws/blob/7.0.0/bin/check-cloudwatch-metric.rb#L58 it strikes me as very odd I need to think about it.

**Comment by majormoses** [comment]
@ay-b I got a fix ready that I tested and it seems to work. If you want to test before someone gets around to reviewing it let me know if you have any issues with it.

**Comment by majormoses** [comment]
well it fixes default but breaks everything else..Will take another look tonight if I have time.

**Comment by majormoses** [comment]
got it this, time would welcome more testing.

**Comment by suncheez** [comment]
@majormoses, yeah, I'd like to participate in testing since I'm very interested in this plugin. I have about 100+ instances to monitor and I need an overall connection count metric.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-aws/versions/7.0.1
