### ISSUE TITLE
AWS check-beanstalk-elb-metric.rb broken

### ISSUE THREAD

**Issue by umairedu** [sensu-plugins/sensu-plugins-aws#257]
./check-beanstalk-elb-metric.rb --help
```/var/lib/gems/2.4.0/gems/sensu-plugins-aws-10.0.0/lib/sensu-plugins-aws/cloudwatch-common.rb:3:in `<module:CloudwatchCommon>': uninitialized constant CloudwatchCommon::Common (NameError)
    from /var/lib/gems/2.4.0/gems/sensu-plugins-aws-10.0.0/lib/sensu-plugins-aws/cloudwatch-common.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
    from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
    from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from ./check-beanstalk-elb-metric.rb:30:in `<main>'```

**Comment by majormoses** [comment]
@umairedu thanks for the bug report. Can you provide a little bit more information?

Is this the first time you are setting this up or was it previously working and now broken. I am just trying to see if it was a regression or not. I notice the check is installed outside of the context of sensu embedded ruby. While this is supported it is not recommended. If its possible could you check if you have the same error when using it from an embedded ruby?
