### ISSUE TITLE
check-rds.rb - Aurora Cluster - Failing

### ISSUE THREAD

**Issue by kunjabdas** [sensu-plugins/sensu-plugins-aws#360]
Check failed to run: undefined local variable or method `db_cluster_id' for #<CheckRDS:0x00000000033e0a00>
Did you mean? db_cluster_writer_id, ["/opt/watcher/checks/gems/sensu-plugins-aws-18.4.0/bin/check-rds.rb:324:in `run'", "/opt/watcher/checks/gems/sensu-plugin-4.0.0/lib/sensu-plugin/cli.rb:59:in `block in <class:CLI>'"]

Any help would be appreciated.

**Comment by allankcrain** [comment]
There'a a bug in the code. This pull request (opened back in June) fixes it, but hasn't yet been merged in: https://github.com/sensu-plugins/sensu-plugins-aws/pull/348
